# Generated by Django 3.0.2 on 2020-07-15 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ipadd', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('portapi', models.IntegerField(default=0)),
                ('portssh', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'mikrotik_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('pminlimitup', models.CharField(max_length=200)),
                ('pminlimitdown', models.CharField(max_length=200)),
                ('pmaxlimitup', models.CharField(max_length=200)),
                ('pmaxlimitdown', models.CharField(max_length=200)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikrotik.profile')),
            ],
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('cminlimitup', models.CharField(max_length=200)),
                ('cminlimitdown', models.CharField(max_length=200)),
                ('cmaxlimitup', models.CharField(max_length=200)),
                ('cmaxlimitdown', models.CharField(max_length=200)),
                ('dedicated', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.parent')),
                ('routers', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.profile')),
            ],
            options={
                'db_table': 'mikrotik_child',
                'managed': True,
            },
        ),
    ]
