# Generated by Django 3.0.2 on 2020-08-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='influx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('ports', models.IntegerField(default=0)),
                ('database', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ipadd', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('portapi', models.IntegerField(default=0)),
                ('portssh', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'mikrotik_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='toogle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_working', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('pminlimitup', models.CharField(max_length=200)),
                ('pminlimitdown', models.CharField(max_length=200)),
                ('pmaxlimitup', models.CharField(max_length=200)),
                ('pmaxlimitdown', models.CharField(max_length=200)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikrotik.profile')),
            ],
        ),
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odedicated', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.parent')),
                ('oinflux', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.influx')),
                ('orouter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.profile')),
                ('oshared', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='odedicated', to='mikrotik.parent')),
            ],
        ),
    ]
