# Generated by Django 3.0.2 on 2020-07-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('othreshold', models.CharField(max_length=200)),
                ('orouter', models.CharField(max_length=200)),
                ('oqueue', models.CharField(max_length=200)),
                ('ominlimitup', models.CharField(max_length=200)),
                ('ominlimitdown', models.CharField(max_length=200)),
                ('omaxlimitup', models.CharField(max_length=200)),
                ('omaxlimitdown', models.CharField(max_length=200)),
            ],
        ),
    ]
