# Generated by Django 3.0.2 on 2020-07-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0003_auto_20200717_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='oqueue',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='orouter',
            field=models.CharField(max_length=200),
        ),
    ]
