# Generated by Django 3.0.2 on 2020-07-17 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0004_auto_20200717_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='oqueue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.child'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='orouter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.profile'),
        ),
    ]
