# Generated by Django 3.0.2 on 2020-07-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0006_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='ddate',
            field=models.DateField(blank=True),
        ),
    ]
