# Generated by Django 3.0.2 on 2020-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0008_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='toogle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_working', models.BooleanField(default=False)),
            ],
        ),
    ]
