# Generated by Django 3.0.2 on 2020-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0010_auto_20200728_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='omedlimitdown',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='configuration',
            name='omedlimitup',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
