# Generated by Django 3.0.2 on 2020-08-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0012_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
