# Generated by Django 3.0.2 on 2020-08-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0013_auto_20200801_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
