# Generated by Django 3.0.2 on 2020-08-04 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0014_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='oqueue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.parent'),
        ),
    ]
