# Generated by Django 3.0.2 on 2020-08-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0015_auto_20200804_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='omedlimitdown',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='omedlimitup',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='othreshold',
        ),
    ]
